### ISSUE TITLE
what are the package requirements versions?

### ISSUE THREAD

**Issue by BarfingLemurs** [04RR/LLM-Trainer#1]
Hi, thanks for the scripts! I want to train the stable3b, but I am having compatibility issues on Ubuntu 22.04. 

```
python lora_train.py 
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
CUDA extension not installed.
CUDA extension not installed.
trainable params: 8710144 || all params: 1535376384 || trainable%: 0.5672969892442998
Traceback (most recent call last):
  File "/home/user/LLM-Trainer/lora_train.py", line 89, in <module>
    data = pd.read_csv(config["data_csv_path"])
                       ~~~~~~^^^^^^^^^^^^^^^^^
TypeError: 'LoraConfig' object is not subscriptable
```

These are my package versions. Does it work correctly on your end?

Used (https://huggingface.co/datasets/KendrickPham/fine-tuning-csv) this dataset

 transformers
Version: 4.36.0.dev0

bitsandbytes
Version: 0.41.2.post2

 peft
Version: 0.6.2

**Comment by 04RR** [comment]
Hey, thanks for pointing this out. 
This was a bug that has now been fixed. Please try it now and let me know how it goes.

**Comment by BarfingLemurs** [comment]
Thanks, that appears to have solved the previous issue. I appear to be getting some errors related to processing, do you have a better dataset example to use?

I have set:

data_column_name: "content"

```
python lora_train.py 
You are using an old version of the checkpointing format that is deprecated (We will also silently ignore `gradient_checkpointing_kwargs` in case you passed it).Please update to the new format on your modeling file. To use the new format, you need to completely remove the definition of the method `_set_gradient_checkpointing` in your model.
trainable params: 8710144 || all params: 1535376384 || trainable%: 0.5672969892442998
Map: 100%|███████████████████████████| 752/752 [00:00<00:00, 8751.08 examples/s]
Traceback (most recent call last):
  File "/home/user/LLM-Trainer/lora_train.py", line 104, in <module>
    trainer.train()
  File "/home/user/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 1556, in train
    return inner_training_loop(
           ^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/accelerate/utils/memory.py", line 136, in decorator
    return function(batch_size, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 1640, in _inner_training_loop
    self.create_optimizer_and_scheduler(num_training_steps=max_steps)
  File "/home/user/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 927, in create_optimizer_and_scheduler
    self.create_optimizer()
  File "/home/user/miniconda3/lib/python3.11/site-packages/transformers/trainer.py", line 974, in create_optimizer
    self.optimizer = optimizer_cls(optimizer_grouped_parameters, **optimizer_kwargs)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/miniconda3/lib/python3.11/site-packages/bitsandbytes/optim/adamw.py", line 12, in __init__
    super().__init__( "adam", params, lr, betas, eps, weight_decay, optim_bits, args, min_8bit_size, percentile_clipping, block_wise, is_paged=is_paged )
  File "/home/user/miniconda3/lib/python3.11/site-packages/bitsandbytes/optim/optimizer.py", line 343, in __init__
    if not 0.0 <= lr:
           ^^^^^^^^^
TypeError: '<=' not supported between instances of 'float' and 'str'
```

**Comment by 04RR** [comment]
Oops, should have stress tested the code before publishing. The bug has been fixed thank you for pointing it out!

**Comment by BarfingLemurs** [comment]
works, ty! 👍
